<?php

/**
 * CI only (M12): creates the databases and the three least-privilege users on a throwaway CI database server,
 * exactly as docs/development/SETUP.md describes for a real install. Waits up to 90 s for the server.
 * Usage: php ci/db-setup.php <host> <root_password> <app_pass> <migrator_pass> <test_pass>
 */

declare(strict_types=1);

if (PHP_SAPI !== 'cli' || $argc !== 6) {
    fwrite(STDERR, "usage: php ci/db-setup.php <host> <root_password> <app_pass> <migrator_pass> <test_pass>\n");
    exit(2);
}
[, $host, $rootPass, $appPass, $migratorPass, $testPass] = $argv;

mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
$db = null;
for ($i = 0; $i < 90 && $db === null; $i++) {
    try {
        $db = new mysqli($host, 'root', $rootPass, '', 3306);
    } catch (mysqli_sql_exception) {
        sleep(1);
    }
}
if ($db === null) {
    fwrite(STDERR, "database server not reachable\n");
    exit(1);
}
echo 'database server: ' . $db->server_info . "\n";

// Passwords are random hex generated by ci/run.sh: safe to inline (CREATE USER does not accept placeholders).
foreach ([$appPass, $migratorPass, $testPass] as $p) {
    if (preg_match('/^[0-9a-f]{32}$/D', $p) !== 1) {
        fwrite(STDERR, "unexpected password format\n");
        exit(2);
    }
}
$statements = [
    'CREATE DATABASE IF NOT EXISTS educloud CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci',
    'CREATE DATABASE IF NOT EXISTS educloud_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci',
    "CREATE USER IF NOT EXISTS 'educloud_migrator'@'%' IDENTIFIED BY '$migratorPass'",
    "CREATE USER IF NOT EXISTS 'educloud_app'@'%' IDENTIFIED BY '$appPass'",
    "CREATE USER IF NOT EXISTS 'educloud_test'@'%' IDENTIFIED BY '$testPass'",
    "GRANT ALL PRIVILEGES ON educloud.* TO 'educloud_migrator'@'%'",
    "GRANT ALL PRIVILEGES ON educloud_test.* TO 'educloud_migrator'@'%'",
    "GRANT SELECT, INSERT, UPDATE, DELETE ON educloud.* TO 'educloud_app'@'%'",
    "GRANT ALL PRIVILEGES ON educloud_test.* TO 'educloud_test'@'%'",
    'FLUSH PRIVILEGES',
];
foreach ($statements as $sql) {
    $db->query($sql);
}
echo "databases and users ready\n";
